/**
 * This file is generated by @docusaurus/plugin-content-docs,
 * and it is not intended to be modified manually.
 */
declare module '@docusaurus/plugin-content-docs' {
  // Add any custom types here if needed
}
